# PUT YOUR CONFIG IN separate files
# in /etc/dracut.conf.d named "<name>.conf"
# SEE man dracut.conf(5) for options
add_dracutmodules+=" crypt dm rootfs-block lvm crypt-gpg "
kernel_cmdline+=" root=UUID=a4202873-80bc-4474-9f7b-eac5e50cc4e8 rd.luks.uuid=4f6f472d-cfb6-45a2-8912-878ce7c9eb88 "

early_microcode="no"
show_modules="yes"
use_fstab="yes"
hostonly="yes"

# NAME                 UUID
# nvme0n1              
# ├─nvme0n1p1          585CE09E5CE077E0
# ├─nvme0n1p3          
# ├─nvme0n1p4          EAFCE649FCE60F9D
# ├─nvme0n1p5          D2CB-03F5
# ├─nvme0n1p6          4f6f472d-cfb6-45a2-8912-878ce7c9eb86
# │ └─root             ft4tmQ-fPYU-u9Vz-q4WK-f14a-hnIv-02mNA0
# │   ├─raven--vg-swap deda2d31-89e4-48df-992c-395ba55abd98
# │   └─raven--vg-root a4202873-80bc-4474-9f7b-eac5e50cc4e8
# └─nvme0n1p2          745D-C19F
# /dev/mapper/raven--vg-swap: UUID="deda2d31-89e4-48df-992c-395ba55abd98" TYPE="swap"
# /dev/nvme0n1p5: LABEL_FATBOOT="BOOT" LABEL="BOOT" UUID="D2CB-03F5" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="ee5160cb-aded-db48-8afe-535d2ce7ef3e"
# /dev/nvme0n1p1: LABEL="WINRE" BLOCK_SIZE="512" UUID="585CE09E5CE077E0" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="b4b33da9-7961-44ae-ae21-aaedfdcc3d13"
# /dev/nvme0n1p6: UUID="4f6f472d-cfb6-45a2-8912-878ce7c9eb88" TYPE="crypto_LUKS" PARTUUID="db07a9cc-a4d5-894f-bdf6-4ce87bc7605f"
# /dev/nvme0n1p4: LABEL="OS" BLOCK_SIZE="512" UUID="EAFCE649FCE60F9D" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="6e28397a-f257-4ac9-b912-1c6630a148ab"
# /dev/nvme0n1p2: UUID="745D-C19F" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="8409636c-a54f-4581-a3e5-458f00b07aba"
# /dev/mapper/raven--vg-root: UUID="a4202873-80bc-4474-9f7b-eac5e50cc4e8" BLOCK_SIZE="4096" TYPE="ext4"
# /dev/loop0: BLOCK_SIZE="131072" TYPE="squashfs"
# /dev/mapper/raven: UUID="ft4tmQ-fPYU-u9Vz-q4WK-f14a-hnIv-02mNA0" TYPE="LVM2_member"
# /dev/sda1: LABEL="GENTOO-AMD6" UUID="1E64-4FD5" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="Main Data Partition" PARTUUID="acce96ee-3ff1-403b-813f-fe71739e9a1f"
# /dev/nvme0n1p3: PARTLABEL="Microsoft reserved partition" PARTUUID="683e4ad4-11da-44e8-9f45-75675d69c044"
